#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "devfileregistry.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "devfileregistry.fullname" . }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: oci-metrics
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: index-metrics
      protocol: TCP
      port: 7071
      targetPort: 7071
  selector:
    app: {{ template "devfileregistry.name" . }}
