#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: Template
metadata:
  name: devfile-registry-acceptance
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: devfile-registry-acceptance-${JOB_NAME}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        containers:
          - image: ${IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: github-mirror-acceptance
            env:
              - name: REGISTRY
                value: ${REGISTRY}
parameters:
- name: IMAGE
  value: quay.io/devfile/devfile-registry-integration
- name: IMAGE_TAG
  value: "next"
  required: true
- name: REGISTRY
  value: "https://registry.stage.devfile.io"
  required: true
- name: JOB_NAME
  generate: expression
  from: "[a-z0-9]{5}"
